### ISSUE TITLE
Turn off Pandas PerformanceWarnings

### ISSUE THREAD

**Issue by hmgaudecker** [janosg/skillmodels#31]
Output from `fit()` is filling up the first few dozen lines with
```
interactiveshell.py:3326: PerformanceWarning: indexing past lexsort depth may impact performance.
```
Of course one may shut it off from the user code, but it might be confusing new users, it is no problem and it will never change. So it should be skillmodels' responsibility.

**Comment by hmgaudecker** [comment]
Seems like this is a more general problem... 

https://github.com/OpenSourceEconomics/estimagic/issues/81

Close here?

**Comment by janosg** [comment]
Yes, this will be solved by estimagic.
