### ISSUE TITLE
Suggestions for renamings of parameters

### ISSUE THREAD

**Issue by hmgaudecker** [janosg/skillmodels#32]
@janosg: Please disapprove where you see fit...

- [x] nemf -> n_mixture_components. Without recursing to the manual, it is impossible to find out what this is (note that all other things here https://skillmodels.readthedocs.io/en/latest/names_and_concepts.html#variables-related-to-dimensions do not have to be specified by the user)
- [x] kappa -> sigma_points_scale. Not described anywhere in docs, sigma_points module API docs do not show up so it is impossible to infer what is meant without looking up the CHS paper
- [x] probanch_function -> prob_anchoring_function. A bit more verbosity helps readability a lot.

Sort-of related: `save_intermediate_optimization_results` and `save_path` seem more useful as optional parameters to the `fit()` method rather than model-level constants. Same comment for `start_params`, `start_values_per_quantity`, `maxiter`, `maxfun`.

**Comment by janosg** [comment]
Probability anchoring was just dropped. I agree with the other renaming proposals. 

Yes, `save_intermediate_optimization_results`, `save_path`, `start_params`, `maxiter` and `maxfun` should actually not be part of skillmodels and definitely not of the model specification but just be passed through to `estimagic.maximize` via the fit method.
